version: '3'
services:
  timeline:
    container_name: timeline
    build:
      context: .
      dockerfile: ./timeline-events/Dockerfile
      args:
        proxy: ""
        sproxy: ""
    restart: unless-stopped
    environment:
      - NODE_ENV=production
  
  collector:
    container_name: collector
    build:
      context: .
      dockerfile: ./event-collector/Dockerfile
      args:
        proxy: ""
        sproxy: ""
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  autocomplete:
    container_name: autocomplete
    build:
      context: .
      dockerfile: ./event-autocomplete/Dockerfile
      args:
        proxy: ""
        sproxy: ""
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  nginx:
    build: ./nginx
    ports:
      - 8080:80
    container_name: nginx
    depends_on: 
      - timeline
      - collector
    restart: unless-stopped