export const RATE_INCREASE = 'RATE_UPGRADE'
export const RATE_DECREASE = 'RATE_DECREASE'

export const TIMELINE_LOADS = 'TIMELINE_LOADS'
export const TIMELINE_ERROR = 'TIMELINE_ERROR'

export const AUTOCOMPLETE_LOADS = 'AUTOCOMPLETE_LOADS'
export const AUTOCOMPLETE_ERROR = 'AUTOCOMPLETE_ERROR'